#       ____                                          _ ____  _
#     / ___|___  _ __ ___  _ __ ___   ___  _ __   __| / ___|| |__   ___  _ __
#    | |   / _ \| '_ ` _ \| '_ ` _ \ / _ \| '_ \ / _` \___ \| '_ \ / _ \| '_ \
#    | |__| (_) | | | | | | | | | | | (_) | | | | (_| |___) | | | | (_) | |_) |
#    \____\___/|_| |_| |_|_| |_| |_|\___/|_| |_|\__,_|____/|_| |_|\___/| .__/
#                                                                      |_|
# config.yml
language: zh_cn
update-check: true
enable-metrics: true

补签卡:
  price: 1
  currency: points
  command: signin retroactivecard give {amount} {player}

# 其他物品可以在这里添加
# 示例：
# 物品名称:
#   price: 价格
#   currency: 货币类型 (points 或 money)
#   command: 执行的命令 (支持变量 {amount} 和 {player})
